// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestIvyInit.Connections.TestIvyInit;

#nullable disable

namespace TestIvyInit.Connections.TestIvyInit.Migrations
{
    [DbContext(typeof(TestIvyInitContext))]
    [Migration("20260425160950_AddSimpleNotes")]
    partial class AddSimpleNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.SimpleNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("simple_notes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
