// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestIvyInit.Connections.TestIvyInit;

#nullable disable

namespace TestIvyInit.Connections.TestIvyInit.Migrations
{
    [DbContext(typeof(TestIvyInitContext))]
    [Migration("20260425162003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.GithubStargazer", b =>
                {
                    b.Property<string>("RepoName")
                        .HasColumnType("text")
                        .HasColumnName("repo_name");

                    b.Property<string>("UserLogin")
                        .HasColumnType("text")
                        .HasColumnName("user_login");

                    b.Property<DateTime?>("StarredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starred_at");

                    b.Property<DateTime?>("UnstarredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unstarred_at");

                    b.HasKey("RepoName", "UserLogin")
                        .HasName("github_stargazers_pkey");

                    b.ToTable("github_stargazers");
                });

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.GithubStargazersDaily", b =>
                {
                    b.Property<string>("RepoName")
                        .HasColumnType("text")
                        .HasColumnName("repo_name");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("NewCount")
                        .HasColumnType("integer")
                        .HasColumnName("new_count");

                    b.Property<int?>("ReactivatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("reactivated_count");

                    b.Property<int?>("UnstarCount")
                        .HasColumnType("integer")
                        .HasColumnName("unstar_count");

                    b.HasKey("RepoName", "Date")
                        .HasName("github_stargazers_daily_pkey");

                    b.ToTable("github_stargazers_daily");
                });

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.GithubStarsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("RepoName")
                        .HasColumnType("text")
                        .HasColumnName("repo_name");

                    b.Property<long?>("Stars")
                        .HasColumnType("bigint")
                        .HasColumnName("stars");

                    b.HasKey("Id")
                        .HasName("github_stars_history_pkey");

                    b.HasIndex(new[] { "RepoName", "Date" }, "github_stars_history_repo_name_date_key")
                        .IsUnique();

                    b.ToTable("github_stars_history");
                });

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.IvyAskQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'manual'::character varying");

                    b.Property<string>("Widget")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("ivy_ask_questions_pkey");

                    b.ToTable("ivy_ask_questions");
                });

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.IvyAskTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("''::text");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("ivy_ask_test_results_pkey");

                    b.HasIndex(new[] { "QuestionId" }, "ix_test_results_question_id");

                    b.HasIndex(new[] { "TestRunId" }, "ix_test_results_run_id");

                    b.ToTable("ivy_ask_test_results");
                });

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.IvyAskTestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Concurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("DifficultyFilter")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'all'::character varying");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'production'::character varying");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("IvyVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<int>("NoAnswerCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("ivy_ask_test_runs_pkey");

                    b.HasIndex(new[] { "IvyVersion" }, "ix_test_runs_ivy_version");

                    b.ToTable("ivy_ask_test_runs");
                });

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.NugetHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<long?>("Downloads")
                        .HasColumnType("bigint")
                        .HasColumnName("downloads");

                    b.Property<string>("PackageName")
                        .HasColumnType("text")
                        .HasColumnName("package_name");

                    b.HasKey("Id")
                        .HasName("nuget_history_pkey");

                    b.HasIndex(new[] { "PackageName", "Date" }, "nuget_history_package_name_date_key")
                        .IsUnique();

                    b.ToTable("nuget_history");
                });

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.IvyAskTestResult", b =>
                {
                    b.HasOne("TestIvyInit.Connections.TestIvyInit.Models.IvyAskQuestion", "Question")
                        .WithMany("IvyAskTestResults")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ivy_ask_test_results_QuestionId_fkey");

                    b.HasOne("TestIvyInit.Connections.TestIvyInit.Models.IvyAskTestRun", "TestRun")
                        .WithMany("IvyAskTestResults")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ivy_ask_test_results_TestRunId_fkey");

                    b.Navigation("Question");

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.IvyAskQuestion", b =>
                {
                    b.Navigation("IvyAskTestResults");
                });

            modelBuilder.Entity("TestIvyInit.Connections.TestIvyInit.Models.IvyAskTestRun", b =>
                {
                    b.Navigation("IvyAskTestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
