// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestIvyInit.Connections.TestIvyInit;

#nullable disable

namespace TestIvyInit.Connections.TestIvyInit.Migrations
{
    [DbContext(typeof(TestIvyInitContext))]
    partial class TestIvyInitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");
#pragma warning restore 612, 618
        }
    }
}
